name: apptemplate
version: 0.1
appVersion: 0.4.0
description: Application Template avec Jhipster.
keywords:
- test
- jhipster
- mariadb
home: https://neo-soft.fr
icon: https://www.google.fr/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiup5-4gLHeAhVSQhoKHbMsANUQjRx6BAgBEAU&url=https%3A%2F%2Fwww.neo-soft.fr%2F&psig=AOvVaw0VFzhfJS5CUdVPYS_NaJzR&ust=1541086414186316
maintainers:
- name: Igor
  email: igor.schadle@neo-soft.fr
